# Generated by Django 4.0.3 on 2022-03-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('incredients', models.TextField()),
                ('directions', models.TextField()),
                ('servings', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
            ],
        ),
    ]
